value1=int(input("enter the any integer : "))
print("Interger: ",value1,"Type: ",type(value1))
value2=float(input("enter any decimal value : "))
print("Float: ",value2,"Type: ",type(value2))
value3=bool(input("enter true or false : "))
print("Boolean: ",value3,"Type: ",type(value3))
value4=(input("enter any string value : "))
print("String: ",value4,"Type: ",type(value4))
value5=list(input("enter item : "))
print("List: ",value5,"Type: ",type(value5))
key=input("enter the key :")
value=input("enter the value :")
value6={key:value}
print("Dictionary: ",value6,"Type: ",type(value6))
value7=set(input("enter numbers  : "))
print("Set: ",value7,"Type: ",type(value7))